debug("MOFO REPORT")
debug("S: " + s(global.selectedPlayaz[IS_GOALIE]) + " " + s(global.selectedPlayaz[IS_DEFENDER]) + " " + s(global.selectedPlayaz[IS_MIDFIELDER]) + " " + s(global.selectedPlayaz[IS_STRIKER]))
debug("D: " + s(global.deadPlayaz[IS_GOALIE]) + " " + s(global.deadPlayaz[IS_DEFENDER]) + " " + s(global.deadPlayaz[IS_MIDFIELDER]) + " " + s(global.deadPlayaz[IS_STRIKER]))
debug("K: " + s(global.killedBy[IS_GOALIE]) + " " + s(global.killedBy[IS_DEFENDER]) + " " + s(global.killedBy[IS_MIDFIELDER]) + " " + s(global.killedBy[IS_STRIKER]))
debug("X: " + s(global.killedBy[IS_GOALIE]-11) + " " + s(global.killedBy[IS_DEFENDER]-11) + " " + s(global.killedBy[IS_MIDFIELDER]-11) + " " + s(global.killedBy[IS_STRIKER]-11))
